In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dishakshi shinde\onedrive\desktop\netflix_pandas_project\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dishakshi shinde\onedrive\desktop\netflix_pandas_project\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp311-cp311-win_amd64.whl (9.9 MB)
Downloading numpy-2.4.3-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 465.5 kB/s eta 0:00:27
   ---------------------------------------- 0.1/12.6 MB 717.5 kB/s eta 0:00:18
    --------------------------------------- 0.2/12.6 MB 1.2 MB/s eta 0:00:11
   - -------------------------------------- 0.6/12.6 MB 2.0 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/12.6 MB 2.9 MB/s eta 0:00:05
   --- ------------------------------------ 1.3/12.6 MB 3.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.9/12.6 MB 5.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.6 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.8/12.6 MB 5.9 MB/s eta 0:00:02
   --------- ------------------------------ 3.0/12.6 MB 5.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 6.0 MB/s eta 0:00:02
   ------------ --------------------------- 3.8/12.6 MB 6.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.6/12.6 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 7.5 MB/s eta 0:00:01
   ----------------- ---------------------- 5.7/12.6 MB 7.5 MB/s eta 0:00:01
   ------------------- -------------------- 6.1/12.6 MB 7.8 MB/s eta 0:00:01
   ------------------- -------------------- 6.1/12.6 MB 7.8 MB/s eta 0:00:01
   --------------------- ------------------ 6.7/12.6 MB 7.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 8.1 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.6 MB 8.1 MB/s eta 0:00:01
   --------------------------- ------------ 8.6/12.6 MB 8.4 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 8.7 MB/s eta 0:00:01
   ------------------------------ --------- 9.5/12.6 MB 8.6 MB/s eta 0:00:01
   ------------------------------- -------- 9.9/12.6 MB 8.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 8.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.4/12.6 MB 11.1 MB/s eta 0:00:01
   -------------------------------------- - 12.0/12.6 MB 10.9 MB/s eta 0:00:01
   -------------------------------------- - 12.2/12.6 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.1 MB/s eta 0:00:00
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.3 pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('netflix_titles.csv')

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.shape

(8807, 12)

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [8]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [9]:
df['country'] = df['country'].fillna('unknown')

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country            0
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [11]:
df = df.dropna(subset=['date_added'])

In [12]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2624
cast             825
country            0
date_added         0
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [13]:
df = df.dropna(subset=['director'])

In [14]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            473
country           0
date_added        0
release_year      0
rating            1
duration          3
listed_in         0
description       0
dtype: int64

In [15]:
df.shape

(6173, 12)

In [16]:
df['cast'] = df['cast'].fillna('Unknown')

In [17]:
df['rating'] = df['rating'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
df['type'].value_counts() #Movies vs TV Shows Analysis

type
Movie      5943
TV Show     230
Name: count, dtype: int64

In [ ]:
df.groupby('release_year')['title'].count() #his shows how many shows were released each

release_year
1942      2
1943      3
1944      3
1945      3
1946      2
       ...
2017    773
2018    760
2019    629
2020    548
2021    297
Name: title, Length: 73, dtype: int64

In [20]:
df['country'].value_counts().head(10) #Top 10 countries with the most content on Netflix

country
United States     2048
India              890
unknown            422
United Kingdom     212
Canada             119
Spain              106
Nigeria             90
Egypt               90
Japan               85
France              81
Name: count, dtype: int64

In [ ]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce') #Strip the extra spaces first, then convert to datetime.

In [28]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
df['year_added'] = df['date_added'].dt.year  #Extract the year for analysis:

In [ ]:
df.groupby('year_added')['title'].count() #Shows how many shows were added to Netflix each year, which can help identify trends in content acquisition.

year_added
2008       1
2009       2
2010       1
2011      13
2012       3
2013       7
2014      18
2015      57
2016     242
2017     854
2018    1214
2019    1418
2020    1315
2021    1028
Name: title, dtype: int64

In [ ]:
df['rating'].value_counts() #Most Common Ratings

rating
TV-MA       2117
TV-14       1457
R            795
TV-PG        538
PG-13        489
PG           286
TV-Y7        132
TV-G         118
TV-Y         112
NR            75
G             41
TV-Y7-FV       4
UR             3
NC-17          2
74 min         1
84 min         1
66 min         1
Unknown        1
Name: count, dtype: int64

In [ ]:
df['listed_in'].value_counts().head(10) #Tfinds the 10 most common genres on Netflix.

listed_in
Dramas, International Movies                        361
Documentaries                                       334
Stand-Up Comedy                                     309
Comedies, Dramas, International Movies              271
Dramas, Independent Movies, International Movies    252
Children & Family Movies, Comedies                  196
Children & Family Movies                            193
Documentaries, International Movies                 179
Dramas, International Movies, Romantic Movies       174
Comedies, International Movies                      173
Name: count, dtype: int64

In [ ]:
pd.pivot_table(
    df,
    values='title',
    index='country',
    columns='type',
    aggfunc='count'
) #Creates a pivot table to analyze the distribution of movies and TV shows by country, which can reveal which countries produce more of each type of content.

type                                                Movie  TV Show
country
, France, Algeria                                     1.0      NaN
Argentina                                            38.0      2.0
Argentina, Brazil, France, Poland, Germany, Den...    1.0      NaN
Argentina, Chile                                      2.0      NaN
Argentina, Chile, Peru                                1.0      NaN
...                                                   ...      ...
Venezuela, Colombia                                   1.0      NaN
Vietnam                                               7.0      NaN
West Germany                                          1.0      NaN
Zimbabwe                                              1.0      NaN
unknown                                             381.0     41.0

[659 rows x 2 columns]

In [ ]:
df.sort_values(by='release_year', ascending=False).head(10) #Find latest content.

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
64,s65,Movie,Nightbooks,David Yarovesky,"Winslow Fegley, Lidya Jewett, Krysten Ritter",unknown,2021-09-15,2021,TV-PG,103 min,Children & Family Movies,Scary story fan Alex must tell a spine-tinglin...,2021
1220,s1221,Movie,Coven of Sisters,Pablo Agüero,"Alex Brendemühl, Amaia Aberasturi, Daniel Fane...","Spain, Argentina",2021-03-11,2021,TV-MA,92 min,"Dramas, Independent Movies, International Movies","Basque Country, 1609. To postpone their execut...",2021
68,s69,Movie,Schumacher,"Hanns-Bruno Kammertöns, Vanessa Nöcker, Michae...",Michael Schumacher,unknown,2021-09-15,2021,TV-14,113 min,"Documentaries, International Movies, Sports Mo...",Through exclusive interviews and archival foot...,2021
71,s72,Movie,A StoryBots Space Adventure,David A. Vargas,"Evan Spiridellis, Erin Fitzgerald, Jeff Gill, ...",unknown,2021-09-14,2021,TV-Y,13 min,Children & Family Movies,Join the StoryBots and the space travelers of ...,2021
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",unknown,2021-09-22,2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...,2021
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,Unknown,unknown,2021-09-22,2021,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...","In the late 1970s, an accused serial rapist cl...",2021
23,s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",unknown,2021-09-21,2021,TV-Y,61 min,Children & Family Movies,From arcade games to sled days and hiccup cure...,2021
1218,s1219,Movie,YES DAY,Miguel Arteta,"Jennifer Garner, Edgar Ramírez, Jenna Ortega, ...",United States,2021-03-12,2021,PG,90 min,"Children & Family Movies, Comedies",A mom and dad who usually say no decide to say...,2021
1195,s1196,Movie,Operation Varsity Blues: The College Admission...,Chris Smith,Matthew Modine,United States,2021-03-17,2021,R,100 min,Documentaries,Reenactments drive this documentary investigat...,2021
1196,s1197,TV Show,Under Suspicion: Uncovering the Wesphael Case,Alain Brunard,Unknown,Belgium,2021-03-17,2021,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries follows the high-profile case ...,2021

In [ ]:
df['content_age'] = df['release_year'].apply(
    lambda x: "Old" if x < 2015 else "New"
) #Classify Old vs New content.

In [ ]:
df.corr(numeric_only=True) #Correlation Analysis: This can help identify if there's any relationship between the release year, the year added to Netflix, and the content age classification.

              release_year  year_added
release_year      1.000000    0.047903
year_added        0.047903    1.000000

In [37]:
df.to_csv("clean_netflix_data.csv", index=False)